baseURL = "https://www.saboya.pro/"
languageCode = "en-us"
title = "Lucas do Amaral Saboya Consultoria"
theme = "resume"
googleAnalytics = "UA-128107458-1"

[params]
author = "CowboySmall"
description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"
primaryColor = "#9580ff"
textPrimaryColor = "#414558"

[params.summary]
enable = true
text = "Experienced Site Reliability Engineer and DevOps specialist with a 15-year IT career that includes success in enhancing DevOps practices to streamline deployment processes, fortify system reliability, and bolster security. Passionate champion for fostering DevOps cultures, reducing failure rates for software releases, and creating seamless experiences for development teams. Effective bilingual communicator with experience in remote roles."

[params.profile]
enable = true
name = "Lucas Saboya"
tagline = "Staff | Lead Site Reliability Engineer"
avatar = "avatar.png"

[params.contact]
enable = true
location = "Fortaleza, Brazil"
[[params.contact.list]]
icon = "fas fa-phone-square"
url = "tel:+5585997794661"
text = "+55 (85) 99779-4661"
[[params.contact.list]]
icon = "fas fa-phone-square"
url = "tel:+14048202125"
text = "+1 (404) 820-2125"
[[params.contact.list]]
icon = "fas fa-envelope-square"
url = "mailto:lucas@saboya.pro"
text = "lucas@saboya.pro"
[[params.contact.list]]
icon = "fas fa-globe"
url = "https://saboya.pro"
text = "saboya.pro"

[params.skills]
enable = true
[[params.skills.list]]
title = "Technical"
[[params.skills.list.items]]
details = "Linux & Unix"
[[params.skills.list.items]]
details = "Containers & Kubernetes"
[[params.skills.list.items]]
details = "Amazon Web Services/Google Cloud Platform"
[[params.skills.list]]
title = "Programing Languages"
[[params.skills.list.items]]
details = "Bash"
[[params.skills.list.items]]
details = "Golang"

[params.languages]
enable = true
[[params.languages.list]]
name = "Brazilian Portuguese"
level = "Native"
[[params.languages.list]]
name = "English"
level = "Fluent"

[params.interests]
enable = true
[[params.interests.list]]
name = "Investing"
[[params.interests.list]]
name = "Travelling"

[params.experience]
enable = true
[[params.experience.list]]
title = "Co-founder"
company = "TrustD Solutions"
dates = "Nov. 2019 - Present"
details = "TrustD Solutions is an SRE and DevOps consultancy founded to bridge the gap between Brazilian workforces and US demand, providing expertise and best practices for public cloud operations, cost optimization, and system reliability." 
[[params.experience.list.items]]
details = "Refactored SRE strategy, introduced tooling, and staffed a DevOps team for a health-tech startup."
[[params.experience.list.items]]
details = "Designed and implemented the company’s full public cloud presence to include runtime infrastructure and CI/CD pipelines for a fintech startup."
[[params.experience.list.items]]
details = "Provided DevOps and SRE consulting services including the design and implementation of underlying infrastructure. For a software development consultancy firm."

[[params.experience.list]]
title = "Staff Site Reliability Engineer"
dates = "Nov. 2019 - Present"
company = "Aetion"
details = "Aetion is a healthcare analytics company that delivers real-world evidence for the manufacturers, purchasers, and regulators of medical treatments and technologies. Recruited by a former coworker as a Senior SRE with work focused on the HITRUST certification effort and earned promotion to Staff SRE role with responsibility for project leadership and mentoring team members." 
[[params.experience.list.items]]
details = "Contributed to successful HITRUST certification efforts with oversight for AWS cloud infrastructure hardening."
[[params.experience.list.items]]
details = "Migrated workloads from AWS ECS to EKS to reduce spending on runtime costs and enabled deployments of Aetion’s platform to client public cloud accounts. "
[[params.experience.list.items]]
details = "Spearheaded Terraform Cloud adoption for AWS infrastructure."
[[params.experience.list.items]]
details = "Maintained a DRY codebase to enable SREs to quickly and reliably provision new environments."
[[params.experience.list.items]]
details = "Accelerated CI/CD pipeline execution and reduced feedback loops for developers. "
[[params.experience.list.items]]
details = "Authored Ansible playbooks, Python scripts, and Golang applications to automate manual, repetitive, and error-prone tasks (e.g. user access provisioning, client infrastructure provisioning, security patching, secret rotation). "

[[params.experience.list]]
title = "Site Reliability Engineer"
dates = "Aug. 2019 - Nov. 2019"
company = "Gainbridge.life"
details = "Gainbridge.life is an insurtech company focused on improving the process of buying and managing annuities and insurance policies. I engaged to lead an SRE team through digital transformation efforts."
[[params.experience.list.items]]
details = "Guided efforts to refactor CI/CD pipelines to enable development team’s migration from microservices to a monolith while maintaining systems availability."
[[params.experience.list.items]]
details = "Leveraged AWS-managed services including EKS, MSK, RDS, and SSM."
[[params.experience.list.items]]
details = "Executed a runtime platform migration from KOPS-managed Kubernetes clusters to EKS."
[[params.experience.list.items]]
details = "Oversaw implementation and adoption of Terraform Cloud and Terraform IaC."
[[params.experience.list.items]]
details = "Introduced observability and telemetry tooling to improve understanding of runtimes in both monolith and microservices environments. "
[[params.experience.list.items]]
details = "Right-sized Kubernetes clusters, node pools, and resource requirements to avoid idle compute resources within clusters while leveraging AWS' spot instances. Efforts led to ~50% reduction in infrastructure costs."

[[params.experience.list]]
title = "Site Reliability Engineer"
dates = "Jan. 2019 - Aug. 2019"
company = "Forestry.io"
details = "Forestry.io builds a content management system for static site generators. I was recruited to design, build, and maintain a new infrastructure architecture to support a planned feature that required execution of several parallel jobs and rendering of static site changes previews on-the-fly."
[[params.experience.list.items]]
details = "Developed operating infrastructure on multiple cloud providers to expedite development workflows via automation. "
[[params.experience.list.items]]
details = "Leveraged Docker containers to package apps and migrated workloads across cloud providers to optimize performance, improve availability, and reduce cloud costs.  "
[[params.experience.list.items]]
details = "Leveraged DigitalOcean’s Managed Kubernetes cluster and GKE clusters. Terraformed Kubernetes clusters on GCP."
[[params.experience.list.items]]
details = "Packaged up workloads to Docker images."
[[params.experience.list.items]]
details = "Built CI/CD pipelines to deploy workloads."

[[params.experience.list]]
title = "Site Reliability Engineer"
dates = "Jan. 2018 - Jan. 2019"
company = "Kairos AR Inc."
details = "Kairos AR builds facial recognition and emotion analysis software powered by AI and ML. Hired as the company’s first SRE to build and maintain all underlying runtime infrastructure and CI/CD pipelines."
[[params.experience.list.items]]
details = "Guided successful migration from AWS into GCP and deployed replicas of the Kairos API and its underlying dependencies to AliCloud."
[[params.experience.list.items]]
details = "Built, deployed, and maintained an MLOps pipeline to support Kairos' latest API improvements and features."
[[params.experience.list.items]]
details = "Created Grafana dashboards to monitor and alert Aerospike deployments that remain the most downloaded today."
[[params.experience.list.items]]
details = "Deployed Tensorflow-based workloads in Kubernetes with GPUs as schedulable units."
[[params.experience.list.items]]
details = "Terraformed Kubernetes clusters on GCP and AWS."
[[params.experience.list.items]]
details = "Built CI/CD pipelines on Jenkins and Travis CI to deploy workloads."

[[params.experience.list]]
title = "Site Reliability Engineer"
dates = "Aug. 2016 - Jan. 2018"
company = "Anki Inc."
details = "Anki was a robotics and AI company best known for consumer-friendly products (Anki Drive & Overdrive, Cozmo robot). Joined to refactor and improve Anki's main website and e-commerce platform's CI/CD pipeline, and transitioned to the platform team focused on API infrastructure. "
[[params.experience.list.items]]
details = "Built and maintained CI/CD pipeline operations using Docker, Ansible, Chef, OpsWorks, Jenkins, and TeamCity."
[[params.experience.list.items]]
details = "Delivered playbooks for provisioning infrastructure for data science and robotics teams."
[[params.experience.list.items]]
details = "Built and maintained Ansible roles and modules to drive Anki cloud infrastructure on AWS."
[[params.experience.list.items]]
details = "Refactored CI/CD pipelines used to deploy Anki’s storefront and website."

[[params.experience.list]]
title = "Site Reliability Engineer"
dates = "Jan. 2016 - Aug. 2016"
company = "HE:labs"
details = "HE:labs is a technology consulting firm focused on digital transformation and software development. Hired in a remote role to an Agile team with work focused on automation to build, package, and deploy Rails apps."
[[params.experience.list.items]]
details = "Partnered with multiple clients in building cloud provider automation to enable faster, highly available, and cheaper solutions to roll out workloads."
[[params.experience.list.items]]
details = "Built Ansible playbooks & automation tools in Python and Ruby."

[[params.experience.list]]
title = "Support Engineer"
dates = "Jan. 2015 - Dec. 2015"
company = "iFactory Solutions"
details = "iFactory is a digital agency specializing in web design, development, and digital marketing. Joined a team responsible for supporting OpenText CEM deployments and AWS for US-based clients."
[[params.experience.list.items]]
details = "Co-authored support, deployment, and maintenance best practices"

[[params.experience.list]]
title = "Computer Networks Analyst"
dates = "Jan. 2008 - Jan. 2015"
company = "Instito Federal do Ceará (IFCE)"
details = "Integrating the Computer Security Incident Response Team - CSIRT, Mitigating IFCE’s network security issues, Managing the Rectory rewalls, Providing level II networking and security support to other campuses tech staff."
[[params.experience.list.items]]
details = "IPv6 networks deployment"
[[params.experience.list.items]]
details = "VMWare vSphere deployment"

[params.social]
enable = true

[[params.social.list]]
icon = "fab fa-github-square"
url = "//github.com/lucazz"
title = "@lucazz"
[[params.social.list]]
icon = "fab fa-linkedin"
url = "//linkedin.com/in/lucazz"
title = "in/lucazz"
[[params.social.list]]
icon = "fab fa-twitter-square"
url = "//twitter.com/lucazz"
title = "@lucazz"

[params.education]
enable = false

[params.awards]
enable = false

[params.projects]
enable = false

[params.information]
enable = false 
